Update test-and-merge.yml

diff --git a/.github/workflows/test-and-merge.yml b/.github/workflows/test-and-merge.yml
--- a/.github/workflows/test-and-merge.yml
+++ b/.github/workflows/test-and-merge.yml
@@ -14,14 +14,14 @@ jobs:
         run: npm install
 
       - name: Run tests
-        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
+        run: npm run test
 
       - name: Check for failed tests
         run: |
-          if [ -f "coverage/coverage-summary.json" ]; then
-            failed=$(jq .total.lines.pct < coverage/coverage-summary.json)
-            if [ "$failed" "true" ]; then
-              echo "Some tests failed. Please fix them before merging."
-              exit 1
-            fi
+          if [ -f "test-results.xml" ]; then failed=$(grep -c "<failure" test-results.xml)
+          if [ "$failed" -gt 0 ]; then
+            echo "Some tests failed. Please fix them before merging."
+            exit 1
           fi
+          fi
+
